FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /app

# Copy only the necessary files needed for the build
COPY ./Aspnetcoreapp/Aspnetcoreapp.csproj ./Aspnetcoreapp/
COPY ./ProductLibrary/ProductLibrary.csproj ./ProductLibrary/

RUN dotnet restore ./Aspnetcoreapp/Aspnetcoreapp.csproj
# Copy the rest of the application files
COPY ./Aspnetcoreapp ./Aspnetcoreapp
COPY ./ProductLibrary ./ProductLibrary

# Final stage
FROM base AS final
# ENTRYPOINT ["dotnet", "run", "--project", "Aspnetcoreapp/Aspnetcoreapp.csproj"]
ENTRYPOINT ["tail", "-f", "/dev/null"]
# CMD ["sleep", "infinity"]
# FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
# WORKDIR /app/build

# COPY --from=build /app/build /app/build


# ENTRYPOINT ["dotnet", "Aspnetcoreapp.dll"]
# # CMD ["sleep", "infinity"]


