// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models
{
    public partial class Applications
    {
        public Guid ApplicationId { get; set; }
        [Required]
        [StringLength(235)]
        public string ApplicationName { get; set; }
        [StringLength(256)]
        public string Description { get; set; }
    }
}