// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models
{
    public partial class ErrorLog
    {
        public int ID { get; set; }
        [StringLength(500)]
        public string ErrorMessage { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ErrorDate { get; set; }
        [StringLength(15)]
        public string Clinician { get; set; }
        [StringLength(200)]
        public string URL { get; set; }

       
    }
}