// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models
{
    public partial class RecordChangeType
    {
        public int ID { get; set; }
        [StringLength(50)]
        public string Description { get; set; }
        [StringLength(15)]
        public string ChangeBy { get; set; }
        public int? ChangeType { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ChangeDate { get; set; }
    }
}