// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models
{
    public partial class Roles
    {
        public Guid RoleId { get; set; }
        public Guid ApplicationId { get; set; }
        [Required]
        [StringLength(256)]
        public string RoleName { get; set; }
        [StringLength(256)]
        public string Description { get; set; }
    }
}