// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models
{
    [Table("Time", Schema = "BasicModel")]
    public partial class Time
    {
        [Key]
        [Column(TypeName = "datetime")]
        public DateTime PK_Date { get; set; }
        [StringLength(50)]
        public string Date_Name { get; set; }
    }
}