// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models
{
    public partial class webpages_OAuthMembership
    {
        [StringLength(30)]
        public string Provider { get; set; }
        [StringLength(100)]
        public string ProviderUserId { get; set; }
        public int UserId { get; set; }
    }
}