// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models
{
    public partial class webpages_Roles
    {
        public webpages_Roles()
        {
            webpages_UsersInRoles = new HashSet<webpages_UsersInRoles>();
        }

        public int RoleId { get; set; }
        [Required]
        [StringLength(256)]
        public string RoleName { get; set; }

        [InverseProperty("Role")]
        public virtual ICollection<webpages_UsersInRoles> webpages_UsersInRoles { get; set; }
    }
}